apiVersion: v1
kind: Secret
metadata:
  name: {{ include "anime-metadata-cache.fullname" . }}
  labels:
    app: {{ include "anime-metadata-cache.name" . }}
    chart: {{ include "anime-metadata-cache.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  mysql-user: {{ .Values.app.config.mysql.user | b64enc | quote }}
  mysql-password: {{ .Values.app.config.mysql.password | b64enc | quote }}