apiVersion: v1
kind: Service
metadata:
  name: '{{ include "anime-metadata-cache.fullname" . }}-app'
  labels:
    app: {{ include "anime-metadata-cache.name" . }}
    component: app
    chart: {{ include "anime-metadata-cache.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: {{ include "anime-metadata-cache.name" . }}
    component: app
    release: {{ .Release.Name }}
